name: Auto Crypto Scanner

on:
  schedule:
    - cron: '*/45 * * * *'  # Every 45 minutes
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scanner
      env:
        API_KEY_ALPHA: ${{ secrets.API_KEY_ALPHA }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python app.py

    - name: Commit dashboard update
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/data.json
        git commit -m "Update dashboard data"
        git push
